#!/usr/bin/env bash

set -e
#
# CONFIG="install.conf.yaml"
# DOTBOT_DIR="dotbot"
#
# DOTBOT_BIN="bin/dotbot"
# BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
#
# cd "${BASEDIR}"
# git submodule update --init --recursive "${DOTBOT_DIR}"

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# type brew >/dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# type brew >/dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# type ack >/dev/null 2>&1 || brew install ack
# type ag >/dev/null 2>&1 || brew install the_silver_searcher
type chruby-exec >/dev/null 2>&1 || brew install chruby
# type ruby-install >/dev/null 2>&1 || brew install ruby-install
# type postgres >/dev/null 2>&1 || brew install postgresql
type nvm >/dev/null 2>&1 || curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
