#!/usr/bin/env bash

source ./setup/start.sh
source ./setup/lib.sh

alert "Creating Symlinks to dotfiles..."

sym ~/.jshintrc jshintrc
sym ~/.gemrc gemrc
sym ~/.gitconfig gitconfig
sym ~/.gitignore_global gitignore
sym ~/.prezto prezto/
dup ~/.zsh/themes/itg-text.zsh-theme itg.zsh-theme/itg-text.zsh-theme
sym ~/.scripts scripts/
sym ~/.tmux tmux/
sym ~/.tmux.conf tmux.conf
sym ~/.vim vim/
sym ~/.vimrc vimrc
sym ~/.vimrc.local vimrc.local
sym ~/.zshenv zshenv
sym ~/.zshrc zshrc

alert "installing vim plugins"
vim +PluginInstall +qall

source ./setup/done.sh
